Restart
Alessandro101296/PollingAppProject pull request #2
Opened 2023-04-26 08:23 UTC by Alessandro101296

2023-04-26 12:56 UTC, dsora requested changes
In generale come approccio hai seguito quello di passare la stessa request dal controller al repository (i.e VoteRequest), creando accoppiamento tra i layers, valuta se in alcuni passaggi è possibile fare una traduzione con strutture dati intermedie o magari passare direttamente i valori che servono alla chiamata spacchettata

2023-04-26 12:56 UTC, dsora commented on src/main/java/io/io/controller/PollController.java
> +    @ResponseBody
Qual è la necessità di esplicitare @ResponseBody?

2023-04-26 12:56 UTC, dsora commented on src/main/java/io/io/controller/PollController.java
> +    public List<PollModel> findByUser(@RequestParam(value = "user") long userId) throws NoUserException {
Come mai nel controller c'è un metodo findBy?

2023-04-26 12:56 UTC, dsora commented on src/main/java/io/io/service/ChoiceService.java
> +                choicesId.add(choiceRepo.save(choice).getId());
Domande:

1- che succede se poll.getUser non corrisponde allo user?
2- è necessario fare il controllo con lo user? Per cosa altro lo usi lo user? 

Il metodo scritto così non fa quello che ti aspetti, specialmente sulla condizione dell'if, sai dirmi qual è il motivo?

2023-04-26 12:56 UTC, dsora commented on src/main/java/io/io/service/PollService.java
> +        response.setUserId(poll.getUser().getId());
Perché questa set è fuori da MapStruct? già che ci sei formalizzala in mapstruct

2023-04-26 12:56 UTC, dsora commented on src/main/java/io/io/service/UserService.java
> +        userRepo.save(user);
Controlli sempre che i valori non siano null, quindi non è ammesso null per sbiancare i campi? O non sono sbiancabili?

2023-04-26 13:01 UTC, Alessandro101296 commented on src/main/java/io/io/controller/PollController.java
> +    public List<PollModel> findByUser(@RequestParam(value = "user") long userId) throws NoUserException {
E' il metodo per trovare tutti i poll di un utente. 
Non va bene il nome del metodo o non ha senso il metodo in se?

2023-04-26 13:04 UTC, Alessandro101296 commented on src/main/java/io/io/service/ChoiceService.java
> +                choicesId.add(choiceRepo.save(choice).getId());
Per quanto riguarda la prima domanda devo aggiungere le eccezioni perchè volevo prima capire la logica del db e poi mettermi a fare gli exception handler e tutto. 
Il controllo lo faccio perché mi è utile per controllare se l'utente che ha fatto la modifica del poll è lo stesso che lo ha pubblicato. 

Non fa quello che mi aspetto per via del fatto che non ho definito equals per User esplicitamente, giusto?

2023-04-26 13:07 UTC, dsora commented on src/main/java/io/io/controller/PollController.java
> +    @ResponseBody
No no intendevo, di investigare cosa fa la notation e usarla se effettivamente necessario, in linea generale meno siamo ridondanti nel codice, e più il codice è chiaro

2023-04-26 13:08 UTC, Alessandro101296 commented on src/main/java/io/io/service/UserService.java
> +        userRepo.save(user);
Questo controllo lo faccio perché nel dto della richiesta ho i 3 campi, ho ipotizzato che il front end possa mandarmi richieste con dei campi null perchè non devono essere cambiati.  In ogni caso nell'entity io ho usato la notazione notBlank.

2023-04-26 13:08 UTC, dsora commented on src/main/java/io/io/controller/PollController.java
> +    public List<PollModel> findByUser(@RequestParam(value = "user") long userId) throws NoUserException {
In genere i findBy si mettono in repository per l'accesso diretto al dato, in Controller e Service si usano nomi con "get"

2023-04-26 13:16 UTC, dsora commented on src/main/java/io/io/service/ChoiceService.java
> +                choicesId.add(choiceRepo.save(choice).getId());
Però User non lo prendi in input da User stesso? non è un meccanismo di authorization plausibile direi :'D 

Oltre alla definizione dell'equals, l'operatore proprio è diverso, se usi == non fai la stessa cosa di equals. Leggiti 
https://www.baeldung.com/java-equals-method-operator-difference

2023-04-27 12:52 UTC, dsora approved these changes
Una volta risolti i commenti, i nuovi sviluppi falli in un altra PR altrimenti troppe modifiche diventano lunghe da leggere

2023-04-27 12:52 UTC, dsora commented on src/main/java/io/io/dto/CreateChoicesRequest.java
> +
Occhio al packaging, responses e requests non li mettere sotto al package dto

2023-04-27 12:52 UTC, dsora commented on src/main/java/io/io/dto/IdListResp.java
> +public class IdListResp {
Non usare i nomi abbreviati, impattano la leggibilità ed in Java non abbiamo vincoli di lunghezza

2023-04-27 12:52 UTC, dsora commented on src/main/java/io/io/controller/PollController.java
> +    public PollModel getPoll(@RequestParam(value = "poll") long pollId) throws NoPollException {
Se il param si chiama "poll" non è chiaro cosa va passato, sembra il poll intero. Specificherei "pollId" nel nome della variabile

2023-04-27 12:52 UTC, dsora commented on src/main/java/io/io/entity/VoteId.java
> +    @ManyToOne
Questa classe è per l'implementazione della relazione ternaria?

2023-04-27 12:52 UTC, dsora commented on src/main/java/io/io/repository/ChoiceRepo.java
> +public interface ChoiceRepo extends CrudRepository<Choice,Long> {
Anche qui, non usare abbreviazioni

2023-04-27 12:52 UTC, dsora commented on src/main/java/io/io/service/ChoiceService.java
> +                choice.setPoll(poll);
Non c'è un approccio che ti permette di mantenere direttamente il pollId al posto del poll? ti risparmieresti un ciclo e la query della riga 42

2023-04-27 13:12 UTC, Alessandro101296 commented on src/main/java/io/io/entity/VoteId.java
> +    @ManyToOne
Si, ho visto che ci sono due modi per farlo e questo è quello che mi veniva più semplice, è sbagliato il package?

2023-04-27 13:44 UTC, merged